### ISSUE TITLE
List and iterate scheduled tasks

### ISSUE THREAD

**Issue by ilyaglow** [yetship/celerybeatredis#10]
I wonder if anyone besides me is interested in a couple helper functions to list and iterate scheduled tasks.

Something like this:
```diff
diff --git a/redisbeat/scheduler.py b/redisbeat/scheduler.py
index a2e58fc..52f291d 100644
--- a/redisbeat/scheduler.py
+++ b/redisbeat/scheduler.py
@@ -155,3 +155,11 @@ class RedisScheduler(Scheduler):
     def info(self):
         # return infomation about Schedule
         return '    . db -> {self.schedule_url}, key -> {self.key}'.format(self=self)
+
+    def list(self):
+        # return a list with celery.beat.ScheduleEntry objects
+        return [pickle.loads(entry) for entry in self.rdb.zrange(self.key, 0, MAXINT)]
+
+    def itertasks(self):
+        # return a generator of celery.beat.ScheduleEntry objects
+        return (pickle.loads(entry) for entry in self.rdb.zrange(self.key, 0, MAXINT))
```

@yetship, I can send a PR if you wish

**Comment by liuliqiang** [comment]
@ilyaglow  yes，it's really a good feature。

but it seems celery supported it following this docs：[Monitoring and Management Guid](http://docs.celeryproject.org/en/latest/userguide/monitoring.html)

**Comment by ilyaglow** [comment]
Thanks, didn't know about this possibility. Although, it doesn't work for me somehow, the command `celery -A tasks inspect scheduled` returns ` - empty - `, but I suspect a fault on my side.

**Comment by isaqueprofeta** [comment]
Little documentation to help other people, since I got a pretty long time to find it, and the truth is that `celery -A tasks inspect scheduled` does not return data from the Beat schedules, but only the ETA/Countdown properties from the task.

I find myself writing, in the end, this function to list tasks btw:
```python
def list_current_schedule():
    """List the current beat schedule"""
    from redisbeat.scheduler import RedisScheduler
    import jsonpickle

    scheduler = RedisScheduler(app=app)

    data = [
        jsonpickle.decode(entry)
        for entry in scheduler.rdb.zrange(schduler.key, 0, -1)
    ]

    for task in data:
        print("""Task: %s Each: %s"""
              % (task.task, task.last_run_at))
```
