### ISSUE TITLE
请问celery如何动态创建task？

### ISSUE THREAD

**Issue by skydazzle** [yetship/celerybeatredis#11]
目前只能通过@app.task装饰器写死task

**Comment by liuliqiang** [comment]
hello，

would you mind showing more detail about your request？

**Comment by elsagogo** [comment]
Hi, could you please help me with adding timed tasks that can define anytime like by date time, by day of the week, or by month?

**Comment by liuliqiang** [comment]
@elsagong  would you mind show more detail? i'm not sure what you want.

**Comment by elsagogo** [comment]
@yetship 嗨，我的意思是，是否可自定义添加定时执行的任务，比如每天、每月或每年的某个时间执行特定的任务.....我们有项目需要动态实现增删改查的定时任务！感谢

**Comment by liuliqiang** [comment]
@elsagong  Please read the [celery's document](http://docs.celeryproject.org/en/latest/index.html) more carefully. Thanks.

**Comment by elsagogo** [comment]
好的，感谢~
