### ISSUE TITLE
"remove" seems doesn't work

### ISSUE THREAD

**Issue by arraytodd** [yetship/celerybeatredis#15]
I tried to cancel the job by using "scheduler.remove(app)"
but it still go on receiving the task and execute it

**Comment by liuliqiang** [comment]
would you mind show more detail about you code?

i wander what's the type of the `app`, function `remove` should pass a string type, which means the name of the task such as `tasks.add` and it would remove the specified task from celery.

**Comment by arraytodd** [comment]
when I add a task named 'task600000000' using method 'scheduler.add', the pickled string in redis zset is like this below:
1) "ccelery.beat\nScheduleEntry\np0\n(Vtask600000000\np1\nS'app.tasks.task_runner'\np2\ncdatetime\ndatetime\np3\n(S'\\x07\\xe2\\x07\\x0c\\x0b6\\x06\\r\\x82\\xdb'\np4\ntp5\nRp6\nI0\nccelery.schedules\ncrontab\np7\n(S'*/30'\np8\nS'1-23'\np9\nS'*'\np10\nS'1-31'\np11\nS'6-12'\np12\ntp13\nRp14\n(I1\nV600000000\np15\n(I21000001\nI21000012\nI21000013\nI21000015\nI21000014\nI21000020\nI21000018\nI21000019\nI21000021\nI21000022\nI21000023\nI21000024\nI21000025\nI21000026\nI21000027\nI21000028\nI21000029\nI21000030\nI21000031\nI21000032\nI21000033\ntp16\ntp17\n(dp18\n(dp19\ntp20\nRp21\n."

I see the method is implemented as below:
    def remove(self, task_key):
        self.rdb.zrem(self.key, task_key)

The question is that task_key is not what we put into the zset， so the pickled string above couldn't be removed indeed.
then I tried like this, record the rank of task stored, then remove it using zremrangebyrank command. Am i in the right direct? 

    def add(self, **kwargs):
        e = self.Entry(app=current_app, **kwargs)
        self.rdb.zadd(self.key, self._when(e, e.is_due()[1]) or 0, pickle.dumps(e))
        rank = self.rdb.zrank(self.key, pickle.dumps(e))
        self.rdb.set(kwargs.get("name"), rank)
        return True
    def remove_by_task_name(self, task_name):
    	rank = self.rdb.get(task_name)
        self.rdb.zremrangebyrank(self.key, rank, rank)
        self.rdb.delete(task_name)

**Comment by woshihaoren** [comment]
remove seems del all task

**Comment by qiankun1024** [comment]
这么明显的功能bug，也是服了。。。
