### ISSUE TITLE
redisbeat 1.1.0 does not have the latest changes for python3 

### ISSUE THREAD

**Issue by svajipay** [yetship/celerybeatredis#18]
When using the library via pip install redisbeat, I see errors related to sys.maxint, which changed in python3.  it works fine if I pull the code and install. 
Is this not updated ? Shows an old date of March 2017.
https://pypi.org/project/redisbeat/

**Comment by liuliqiang** [comment]
which python3 version do you used?
i try in Python 3.6.6, it works well..

```
(py3) ➜  ~ python --version       
Python 3.6.6
(py3) ➜  ~ pip install redisbeat  
Collecting redisbeat
Installing collected packages: redisbeat
Successfully installed redisbeat-1.1.0
```

**Comment by svajipay** [comment]
Using python3.5. redisbeat installs fine. Its just that it does not have the latest code which addressed python3 changes. The March 17th date on the package seems like it is really old.

**Comment by liuliqiang** [comment]
it's still under maintaining, i'm sorry for not add auto push trigger to pypi.
I just add commit to do this by traivis.
