### ISSUE TITLE
第80行的task为bytes类型

### ISSUE THREAD

**Issue by zhj0513** [yetship/celerybeatredis#38]
第80行debug日志报错
启动前配置的周期任务如下：
![IMG_20230328_091542.jpg](https://user-images.githubusercontent.com/25121534/228101508-00d01aa4-c7ff-43f1-97a3-6104f051643f.jpg)

**Comment by liuliqiang** [comment]
hihi @zhj0513 ,

would you mind to provide more information about your issue?

python version:
celery version:
redis version:

**Comment by zhj0513** [comment]
python：3.6.5
celery：5.1.2
redis(服务)：5.0.7   redis(pypi): 3.5.2
或许是我用的这些版本太高了🤔
另外发现的问题是，添加crontab（hour=9，minute=30）这种定时任务，任务不会被调度。
添加crontab（minute='*'）每分钟执行的任务，可以被调度

试了代码中的example，是可以添加crontab（hour=16，minute=23）这种的:
![image](https://user-images.githubusercontent.com/25121534/228306526-ddfc855c-183f-493c-8853-ab7a206879df.png)
docker容器里的redis(pypi)3.3.8版本的，redis（服务）为7.0.x，因此我感觉是redis（pypi）版本的问题

我的英语不行，望up主见谅,，我没有删除issue权限，届时请您帮忙删除此issue😬
