### ISSUE TITLE
Is there a remove or adjust example?

### ISSUE THREAD

**Issue by syfqcom** [yetship/celerybeatredis#4]
This package is very convenient,
but i didn't find remove or adjust example.
Could you write a remove or adjust example?
Thank you !
你好，这个包真的很方便，
但我没有发现有删除或调整任务的示例，
请问可以给出一些删除或调整任务的示例吗？

**Comment by liuliqiang** [comment]
yes, i have just push the example for dynamic remove task,
as modify task dynamic, it may be implement in several time before, if you're interested in it, just take a pr, this project welcome all people to join in...  😄
