### ISSUE TITLE
version 1.2.5 is broken

### ISSUE THREAD

**Issue by jma** [yetship/celerybeatredis#40]
Using the version 1.2.5, I got the following error:
```
  File "/home/runner/.cache/pypoetry/virtualenvs/rero-ils-dOBfF0Z2-py3.9/lib/python3.9/site-packages/redisbeat/scheduler.py", line 95
    debug("old_entries: %s",old_entries_dict))
```

**Comment by liuliqiang** [comment]
hi @jma I have confirm it's a bug in the code.

And the release the latest version 1.2.6 to fix it.

Sorry for your inconvenience.

**Comment by jma** [comment]
Many thanks.
