### ISSUE TITLE
dynamically add task has problem！！！

### ISSUE THREAD

**Issue by timosir** [yetship/celerybeatredis#6]
hi ,author
   when i execute  python add_task.py  ,first has a error 
2017-09-04 17:55:12,343: ERROR/MainProcess] Received unregistered task of type u'tasks.sub3'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or m /aybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
'[[99, 100], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]' (84b)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/celery/worker/consumer/consumer.py", line 559, in on_task_received
    strategy = strategies[type_]
KeyError: u'tasks.sub3'

but,when i  restart (celery worker and celery beat) it  ,it will work properly ，why is that ?? 

remove_task.py  the same mistake ,
Look forward to your reply

**Comment by liuliqiang** [comment]
nice to get your feedback @timosir 
would you mind show us your code ? 
as your description in the issue, i found you add the task 'tasks.sub3', however, in my `add_task.py` there's only 'tasks.sub' exists not 'tasks.sub3', have you ever change the code?

**Comment by timosir** [comment]
yes,i change your code.
add_task.py 
#!/usr/bin/env python
# encoding: utf-8
from datetime import timedelta

from redisbeat.scheduler import RedisScheduler

from tasks import app


if __name__ == "__main__":
    schduler = RedisScheduler(app=app)
    schduler.add(**{
        'name': 'sub-perminute2',
        'task': 'tasks.sub3',
        'schedule': timedelta(seconds=3),
        'args': (99, 100)
    })
############################
task.py
@app.task
def add(x, y):
    return x + y


@app.task
def sub(x, y):
    return x - y

@app.task
def sub1(x, y):
    return x * y


@app.task
def sub2(x, y):
    return x * y

@app.task
def sub3(x, y):
    return x * y
because ,i have many new task need add. so i change code .

**Comment by liuliqiang** [comment]
maybe you can beauty your code for better debug...  lol..

both with **Tab** or

 \`\`\`
code
\`\`\`

are ok

**Comment by timosir** [comment]
#!/usr/bin/env python
# encoding: utf-8
from datetime import timedelta
from redisbeat.scheduler import RedisScheduler
from tasks import app
if __name__ == "__main__":
       schduler = RedisScheduler(app=app)
        schduler.add(**{
        'name': 'sub-perminute2',
        'task': 'tasks.sub3',
        'schedule': timedelta(seconds=3),
        'args': (99, 100)
    })
