### ISSUE TITLE
When can I add a support for amqp function, not just redis?

### ISSUE THREAD

**Issue by Feeeenng** [yetship/celerybeatredis#8]
l want to support amqp.
example : rabbitmq

**Comment by liuliqiang** [comment]
currently, i have no plan for add support for amqp.

However, i found it in Celery 4.1.0, celery support dynamic add task now with a little trouble. Detail for docs： [Periodic Tasks](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#entries)

**Comment by grunmin** [comment]
@yetship It's not really dynamic

**Comment by liuliqiang** [comment]
No plan to support amqp.
